### ISSUE TITLE
[Bug] - Degraded Performance on AL2023 comparing to AL2

### ISSUE THREAD

**Issue by nadavbuc-orchid** [amazonlinux/amazon-linux-2023#855] opened 2024-12-03 07:17 UTC
**Describe the bug**
We are running Local Github Runners over Kubernetes
We discovered that running node based scripts in the runners freeze when using AL2023 but worked perfectly well on AL2

**To Reproduce**
1. Use Karpenter and set instance type to m7i.2xlarge and AMIFamily to AL2023
2. Run Heavy Duty nodejs github task
3. The github task stops responding and the log seems to freeze in github actions ui for hours
4. Do the same with AL2 and alias al2@latest - everything works

**Expected behavior**
There should be no performance or otherwise implications when using AL2023
The node load average should not affect connectivity or network usability no matter which AMI is being used

**Screenshots**
ON AL2023 you can see the task idle for 15 minutes
![image](https://github.com/user-attachments/assets/cb0d2eb5-3397-4fb0-aa25-dcc7ae059f48)
ON AL2 you can see task took less then a minute to complete
![image](https://github.com/user-attachments/assets/7a069793-db87-4163-ad7f-c23c8a8c05a3)

This has been tested multiple times to verify

**Comment by sgleske-ias** [comment] 2024-12-04 17:39
This bug report is likely related to mine https://github.com/amazonlinux/amazon-linux-2023/issues/856

**Comment by stewartsmith** [comment] 2024-12-26 20:51
Likely duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/840

**Closed by stewartsmith** 2024-12-26 20:51 UTC
Labels: bug, duplicate, kernel
