### ISSUE TITLE
[Package Request] PHP Sodium

### ISSUE THREAD

**Issue by nwtben** [amazonlinux/amazon-linux-2023#204] opened 2022-10-10 14:08 UTC
What package is missing from Amazon Linux 2022? Please describe and include package name.
php-sodium

Is this an update to existing package or new package request?
new package request

Is this package available in Amazon Linux 2?
yes

**Comment by patricksebastien** [comment] 2023-03-31 17:24
Useful to make a API with Laravel framework using laravel/passport

**Comment by ozbenh** [comment] 2023-04-03 01:38
I assume it replies on `libsodium` ? We have actually removed that one purposefully as nothing good comes from yet-another-crypto-library especially when it comes to security, compliance, and things like FIPS. We'll keep track of the requests nonetheless, thanks for the feedback.

**Comment by kpsoaren** [comment] 2023-04-12 18:18
Laravel is a widely-used framework. Not including php-sodium and libsodium will keep us and many many other businesses from adopting AL2023.

**Comment by ozbenh** [comment] 2023-04-12 22:24
`libsodium` is also absent from other enterprise distros. As far as I know it isn't in any shape to be FIPS certified. Note that you always have the option of building the required dependencies from sources.

**Comment by ArronKing** [comment] 2023-04-13 09:36
I had this problem too, if it helps any other PHP users here's how to get sodium installed on AL2023:

```
sudo yum install php8.1-devel php-pear gcc
wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
// verify the file integrity https://libsodium.gitbook.io/doc/installation#integrity-checking
tar -xvzf LATEST.tar.gz
cd libsodium-stable
./configure
make && make check
sudo make install
sudo pecl install -f libsodium
//add extension=sodium.so to php.ini
```

**Comment by rajjanorkar** [comment] 2023-04-25 01:34
This is something we really need! Thank you

**Comment by neilcook** [comment] 2023-06-16 11:06
> I assume it replies on `libsodium` ? We have actually removed that one purposefully as nothing good comes from yet-another-crypto-library especially when it comes to security, compliance, and things like FIPS. We'll keep track of the requests nonetheless, thanks for the feedback.

"Nothing good". Except being able to run all the software that makes use of it. Heaven forfend that AL2023 should give developers a choice of crypto algorithms and implementations. And FIPS compliance is of course a requirement for every use-case for every application around the world. Oh wait.

**Comment by BernardRobbins** [comment] 2023-07-25 17:10
As an addon to @ArronKing excellent instructions
echo extension=sodium.so | sudo tee /etc/php.d/20-sodium.ini
# clean up
sudo dnf autoremove php8.1-devel gcc

**Comment by ozbenh** [comment] 2023-08-11 01:05
We are evaluating inclusion of this package in our next quarterly release

**Comment by faizanakram99** [comment] 2023-08-22 17:56
It is missing again in amazon linux 2023 (elastic beanstalk php platform), i am amazed by the stupidity of aws here. The extension is shipped with php since version 7.2 by default and it is missing from latest amazon linux :man_shrugging: 

Guess we would have to move to a different cloud provider once php 8.1's is EOL.

**Comment by stewartsmith** [comment] 2023-08-22 18:39
FYI: I've deleted a comment on this issue that wasn't being respectful.

A reminder from CONTRIBUTING.me:
> This project has adopted the [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct).
For more information see the [Code of Conduct FAQ](https://aws.github.io/code-of-conduct-faq) or contact
opensource-codeofconduct@amazon.com with any additional questions or comments.

**Comment by faizanakram99** [comment] 2023-08-22 18:59
> FYI: I've deleted a comment on this issue that wasn't being respectful.
> 
> A reminder from CONTRIBUTING.md:
> 
> > This project has adopted the [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct).
> > For more information see the [Code of Conduct FAQ](https://aws.github.io/code-of-conduct-faq) or contact
> > [opensource-codeofconduct@amazon.com](mailto:opensource-codeofconduct@amazon.com) with any additional questions or comments.

What exactly was disrespectful and towards whom in that comment? And which rule from coc did it break?

Something which is part of core PHP since  version 7.2 is missing from the latest images of Amazon, the ones shipping PHP 8.2, how is calling it out disrespectful?

**Comment by faizanakram99** [comment] 2023-08-22 19:02
> I had this problem too, if it helps any other PHP users here's how to get sodium installed on AL2023:
> 
> ```
> sudo yum install php8.1-devel php-pear gcc
> wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
> // verify the file integrity https://libsodium.gitbook.io/doc/installation#integrity-checking
> tar -xvzf LATEST.tar.gz
> cd libsodium-stable
> ./configure
> make && make check
> sudo make install
> sudo pecl install -f libsodium
> //add extension=sodium.so to php.ini
> ```

Thank you @ArronKing for making al2023 useable.

**Comment by BernardRobbins** [comment] 2023-08-22 19:03
> What exactly was disrespectful

Calling the team stupid. And the rest of your comment was vapid.

**Comment by faizanakram99** [comment] 2023-08-22 19:07
> > What exactly was disrespectful
> 
> Calling the team stupid. And the rest of your comment was vapid.

I called the action as stupid, not the team. The action of not shipping core extensions.

**Comment by faizanakram99** [comment] 2023-08-22 19:28
Okay, I have come to realize that I might have overreacted a bit, and if I hurt someone in the process, I apologize.

**Comment by ozbenh** [comment] 2023-08-23 00:40
The problem isn't the extension, the problem is `libsodium` which we don't currently ship. This is being looked at and considered for an upcoming quarterly release

**Comment by Frtrillo** [comment] 2023-09-06 11:49
> The problem isn't the extension, the problem is `libsodium` which we don't currently ship. This is being looked at and considered for an upcoming quarterly release

Thanks, waiting for it, laravel passport is a complete package even if it uses that library for crypto

**Comment by ozbenh** [comment] 2023-09-13 06:26
You might want to consider waiting for the upcoming quarterly release....

**Comment by victorPetrescuZonk** [comment] 2023-09-19 09:18
This is a core package... pls. add it. Many major frameworks are impacted (ex Symfony, Laravel).

**Comment by ozbenh** [comment] 2023-09-21 00:32
`php-sodium` has now been released as part of AL2023.2 for php 8.2 as a separate subpackage `php8.2-sodium`

**Closed by ozbenh** 2023-09-21 00:32 UTC
Labels: enhancement, packages, pending

**Comment by MrTschi** [comment] 2023-12-27 21:45
@ozbenh any chance that it will also be published for 8.1? Magento2 has this as a dependency..

**Comment by limmike** [comment] 2024-03-08 01:47
for php 8.1, you can build it
```
              dnf install -y php-devel php-pear gcc
              pear update-channels
              pecl update-channels

                dnf install -y libsodium-devel
                yes 'no' | pecl install -f libsodium
                echo 'extension=sodium.so' > /etc/php.d/20-sodium.ini
```
run the above comments as root

**Comment by ozbenh** [comment] 2024-08-28 00:06
I am not certain what codebuild is doing here . I have an AL2023 instance with the same package versions installed that you listed above and:
```
$ php -m | grep sodium 
sodium
```
Now, this is directly run by ssh'ing into the instance.

From the logs you pasted, it seems it's looking for things in `.phpenv/versions/...` and not in the system library path, which is ... odd. I would suggest opening an issue with CodeBuild here.

**Comment by shaunak-thea** [comment] 2024-12-10 20:58
@Dad75 

I have been facing the same bug as yours and was able to manually move the sodium module into the directory that PHP queries

```
       - yum install -y php8.2-sodium
       - echo "extension=sodium" > /root/.phpenv/versions/8.2.20/etc/conf.d/sodium.ini
       - EXTENSION_DIR=$(php -i | awk -F "=> " '/^extension_dir/ {print $2}')
       - cp /usr/lib64/php8.2/modules/sodium.so $EXTENSION_DIR
```

**Comment by Tlapi** [comment] 2025-01-29 22:36
Now sodium is missing on the fresh PHP 8.4 release

**Comment by faizanakram99** [comment] 2025-01-30 06:02
> Now sodium is missing on the fresh PHP 8.4 release

Are you sure?

Which Amazon Linux are you on?

**Comment by Tlapi** [comment] 2025-02-01 10:32
This is PHP 8.4 running on 4.5.0, released at the end of January 2025. I cant install the same app running on "PHP 8.3 running on 64bit Amazon Linux 2023/4.4.2"
