### ISSUE TITLE
[Package Request] - qemu

### ISSUE THREAD

**Issue by ShivanshVij** [amazonlinux/amazon-linux-2023#603] opened 2024-01-07 23:59 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

`qemu` - https://qemu.org

QEMU is a generic and open source processor emulator which achieves a good
emulation speed by using dynamic translation. 

**Is this an update to existing package or new package request?**

A new package request.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

Yes, it is available: https://amazonlinux.pkgs.org/2/amazonlinux-core-x86_64/qemu-3.1.0-8.amzn2.0.8.x86_64.rpm.html

**Any additional information you'd like to include. (use-cases, etc)**

Being able to emulate VMs via nested virtualization is a supported use-case on Amazon Metal EC2 Instances. Without having QEMU available, this capability is severely hampered.

**Comment by stewartsmith** [comment] 2024-01-11 16:19
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/479 - userspace packages supporting KVM host functionality

**Closed by stewartsmith** 2024-01-11 16:19 UTC
Labels: duplicate, enhancement, packages
