### ISSUE TITLE
[Package Request] - Postgresql 16

### ISSUE THREAD

**Issue by Marcholio** [amazonlinux/amazon-linux-2023#638] opened 2024-02-20 10:02 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

Postgresql v16

**Is this an update to existing package or new package request?**

Major update to existing package. 15 is currently installed, but 16 is already available in RDS.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

N/A

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by stewartsmith** [comment] 2024-02-20 21:55
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/516 - so we'll track there.

**Closed by stewartsmith** 2024-02-20 21:55 UTC
