### ISSUE TITLE
[Package Request] - FreeIPA (specifically ipa-client)

### ISSUE THREAD

**Issue by dustinjohnson9** [amazonlinux/amazon-linux-2023#503] opened 2023-10-05 22:00 UTC
Support for ipa-client is crucial for directory management in AL2023. Can we have this package added?

**Comment by stewartsmith** [comment] 2023-10-06 14:18
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/36

**Closed by stewartsmith** 2023-10-06 14:18 UTC
