### ISSUE TITLE
[Package Request] - Python 3.12

### ISSUE THREAD

**Issue by ccassidy-maxar** [amazonlinux/amazon-linux-2023#583] opened 2023-12-15 15:49 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Python 3.12

**Is this an update to existing package or new package request?**
Update

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
N/A

**Any additional information you'd like to include. (use-cases, etc)**
With the release of Python 3.12 on Lambda it would be ideal to have the versions on AL2023 and Lambda in sync.  Thanks!
https://aws.amazon.com/about-aws/whats-new/2023/12/aws-lambda-support-python-3-12/

**Comment by stewartsmith** [comment] 2023-12-15 15:58
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/483 - will close this issue and track there.

**Closed by stewartsmith** 2023-12-15 15:58 UTC

**Comment by ccassidy-maxar** [comment] 2023-12-15 15:59
Thanks, missed that one!
