### ISSUE TITLE
[Feature Request] - GUI For Amazon Linux 2023

### ISSUE THREAD

**Issue by JorgeGarciaEnki** [amazonlinux/amazon-linux-2023#381] opened 2023-06-17 18:07 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes you have to use a GUI when your application needs it.

**Describe the solution you'd like**
The option to run a GUI like MATE or GNOME.

**Describe alternatives you've considered**
Currently no alternatives or use another variant like Ubuntu.

**Additional context**
Some applications need some GUI to run installers or configuration wizards, even when their execution may be by services, the first steps are graphical.

**Comment by stewartsmith** [comment] 2023-06-22 21:23
Closing as duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/47

**Closed by stewartsmith** 2023-06-22 21:23 UTC
