### ISSUE TITLE
[Feature Request] - Run Amazon Linux 2023 as a virtual machine on premises

### ISSUE THREAD

**Issue by Manouchehri** [amazonlinux/amazon-linux-2023#102] opened 2022-03-16 00:14 UTC
**Is your feature request related to a problem? Please describe.**
Creation of Amazon Linux 2022 virtual machine (VM) images for on-premises development and testing. e.g. the same as: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html

**Describe the solution you'd like**
This URL to be valid:

https://cdn.amazonlinux.com/os-images/2022/kvm/

**Describe alternatives you've considered**
I can probably figure out how to make my own bootstrapped install using `dnf install --installroot=/mnt`, but it would be nice to have an official image to start with.

**Comment by chadbrewbaker** [comment] 2022-03-21 21:15
I'm working on this right now! Trying to get a UTM image for my M1, here are the instructions for Arch: https://ktprograms.codeberg.page/blog/posts/2022-03-17_1750_utm-arch-arm/

The first steps I think can be refactored into an Alpine linux container for x86/ARM. 

- [ ] Build container
- [ ] Image for wsl2 -  upstream to https://github.com/yosukes-dev/AmazonWSL
- [ ] Image for UTM - upstream to https://github.com/utmapp/mac.getutm.app/tree/main/_virtual_machines
- [ ] Image for kvm

**Comment by Manouchehri** [comment] 2022-03-21 21:32
@chadbrewbaker Hmm, not sure I get how that helps with AL2022?

**Comment by liesenml** [comment] 2022-03-23 15:54
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by chadbrewbaker** [comment] 2022-11-08 14:32
Bump. This is nontrivial. I blew another day on it yesterday - need some official AWS help here.

My notes for inspecting Fedora images on macos:

```bash
strings Fedora-Minimal-36-1.5.armhfp.raw | grep RSA "PRIVATE"
xxd -a Fedora-Minimal-36-1.5.armhfp.raw | less
fdisk Fedora-Minimal-36-1.5.armhfp.raw
hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount Fedora-Minimal-36-1.5.armhfp.raw
hdiutil mount /dev/disk5s1
```

From what I can tell AmazonLinux2 used effectively the same grub2 VM structure as Fedora.  https://arm.fedoraproject.org

@iximiuz has project to take the OSI container and stuff a bootloader etc on it: https://github.com/iximiuz/docker-to-linux/issues/25 This might be the most elegant solution.

**Comment by bplessis-swi** [comment] 2023-03-27 08:34
The FAQ still references kvm images as to be provided on the GA release:

```
Q: Can I use AL2023 outside of AWS?

A: AL2023 images can be used outside of AWS, however, these images are not covered by [AWS Support Plans](https://aws.amazon.com/premiumsupport/plans/) when used outside of AWS. When Amazon Linux 2023 becomes Generally Available, it will be provided as a virtual machine image for on-premises use, enabling you to easily develop, test, and certify applications from a local development environment. This option is not available during the preview.
```

Look like someone forgot this ^^

**Comment by nmeyerhans** [comment] 2023-04-04 20:39
Indeed the FAQ did indicate that VM images would be available at GA for use outside of EC2. Let's consider that FAQ entry to be inaccurate, for now.

We are working on VM images and will note their availability in the release notes and resolve this issue when they're available.

**Comment by emboss64** [comment] 2023-05-02 08:16
Any updates on this one? Thanks!

**Comment by yoonjs2** [comment] 2023-05-18 06:01
Any updates? Thanks!

**Comment by Rosch** [comment] 2023-06-28 08:30
I am missing AL2023 in a vmware instance desperately! Is there anything known when this comes to life?

**Comment by rotan-hanrahan** [comment] 2023-06-28 10:40
According to the Wayback Machine, the following text was present on [https://aws.amazon.com/linux/amazon-linux-2023/faqs/](https://aws.amazon.com/linux/amazon-linux-2023/faqs/) in March 2023: 

> When Amazon Linux 2023 becomes Generally Available, it will be provided as a virtual machine image for on-premises use, enabling you to easily develop, test, and certify applications from a local development environment. This option is not available during the preview.

The June 3 snapshot of the same page no longer contains this text, so the promise made during the preview regarding the VM image once AL2023 reaches GA appears to be withdrawn. (Note: the revision of the FAQ was suggested by @nmeyerhans in early April, almost three months ago.)

I see no evidence of any outreach to the community to explain this, nor any requests for technical assistance (assuming the issue is technical). If the issue is bureaucratic in nature, we might never see the promised VM image.

Some clarification from Amazon is overdue.

**Comment by inflatador** [comment] 2023-06-28 16:07
[Red Hat's recent announcement](https://www.redhat.com/en/blog/furthering-evolution-centos-stream) opens a window of opportunity for Amazon Linux to become a major player in the datacenter. Here's hoping Amazon will take advantage of that opportunity, starting with the VM images requested here.

**Comment by tanvp112** [comment] 2023-07-26 06:10
It's becoming more and more difficult to use AL2 now, eg. https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#common-upgrading-issues

**Comment by stewartsmith** [comment] 2023-07-29 03:52
Apologies for the long time radio-silence here, I understand the frustration this must cause, and there's certainly developers like myself who share that frustration.

While this isn't an image, it may be a useful starting point for building your own. Using the pretty neat [kiwi-ng](https://osinside.github.io/kiwi/index.html) with the following config, I can boot to a login prompt. There's a few other things that are missing that turn this into a base image that we'd release (some cloud-init config at least), but it's a starting point.

You'll need this at `root/etc/default/grub`
```
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,115200n8 console=tty0 rd.emergency=poweroff rd.shell=0 selinux=1 security=selinux quiet"
GRUB_TIMEOUT=0
GRUB_DISABLE_RECOVERY="true"
GRUB_TERMINAL="ec2-console"
GRUB_ENABLE_BLSCFG="true"
GRUB_X86_USE_32BIT="true"
GRUB_DEFAULT=saved
GRUB_UPDATE_DEFAULT_KERNEL=true
```

and this at `root/etc/cloud/cloud.cfg.d/02-onprem.cfg`
```
datasource_list: [ NoCloud, AltCloud, ConfigDrive, OVF, None ]
```

and then your `appliance.kiwi` can look like:

```
<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="7.5" name="amazonlinux-2023">
    <description type="system">
        <author>Stewart Smith</author>
        <contact>trawets@amazon.com</contact>
        <specification>Example Amazon Linux 2023 kiwi config</specification>
    </description>
    <profiles>
        <profile name="Virtual" description="Virtual image of Amazon Linux 2023"/>
    </profiles>
    <preferences>
        <version>2.0.0</version>
        <packagemanager>dnf</packagemanager>
        <keytable>us</keytable>
        <timezone>UTC</timezone>
        <rpm-check-signatures>true</rpm-check-signatures>
    </preferences>
    <preferences profiles="Virtual">
      <type image="oem" filesystem="xfs" kernelcmdline="console=ttyS0" firmware="efi" format="qcow2">
            <oemconfig>
                <oem-resize>false</oem-resize>
            </oemconfig>
            <bootloader name="grub2" console="serial" timeout="10"/>
        </type>
    </preferences>
    <repository imageinclude="false" sourcetype="mirrorlist">
      <source path="https://cdn.amazonlinux.com/al2023/core/mirrors/latest/x86_64/mirror.list"/>
    </repository>
    <packages type="bootstrap" patternType="onlyRequired">
      <package name="dnf"/>
      <package name="curl-minimal"/>
      <package name="gnupg2-minimal"/>
    </packages>
    <packages type="image" patternType="onlyRequired">
      <namedCollection name="onprem"/>
      <namedCollection name="onprem-minimal"/>
      <package name="kernel"/>
      <package name="grub2-pc"/>
      <package name="grub2-pc-modules"/>
      <package name="grub2-efi-x64-modules"/>
      <package name="grub2-efi-x64-ec2"/>
      <package name="zstd"/>
      <package name="systemd-networkd"/>
    </packages>
</image>
```

Built on a Fedora 38 instance, and tested with `qemu-system-x86_64 -boot c -net nic -net user  -m 4G -cpu max -smp 4 -hda testboot -bios /usr/share/edk2/ovmf/OVMF_CODE.fd  -nographic` *just* to booting to a Login prompt, and not a moment further.

i.e. this is a starting point for someone to continue what that looks like.

**Comment by tim-ebu** [comment] 2023-08-22 13:00
Hi Stewart

> While this isn't an image, it may be a useful starting point for building your own. 

Are you implying that there will not be official images for on-premises? This and your further comment "this is a starting point for someone to continue what that looks like" does not suggest that AWS intends to supply these images soon.

**Comment by chadbrewbaker** [comment] 2023-08-22 15:41
Apparently you can do this with AWS CLI? https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html

al2023-ami is the keyword apparently?

**Comment by AaronSwearingen** [comment] 2023-08-23 14:50
What OS does AWS recommend for hybrid cloud solutions? AL2 is less then two years away from EOL. AL2023 isn't available as a virtual machine and also presumably isn't supported for use with https://aws.amazon.com/hybrid/ features like ECS/EKS Anywhere.

I appreciate the repo maintainers trying to help out the community, but AWS needs to be made aware this is more than just a community request. There is a real business need to enable companies to leverage (and pay for) AWS hybrid cloud services. Anyone expecting AL2023 to fulfill that need now finds themselves in a position of uncertainty.

**Comment by chadbrewbaker** [comment] 2023-08-23 15:46
> What OS does AWS recommend for hybrid cloud solutions? AL2 is less then two years away from EOL. AL2023 isn't available as a virtual machine and also presumably isn't supported for use with https://aws.amazon.com/hybrid/ features like ECS/EKS Anywhere.
> 
> I appreciate the repo maintainers trying to help out the community, but AWS needs to be made aware this is more than just a community request. There is a real business need to enable companies to leverage (and pay for) AWS hybrid cloud services. Anyone expecting AL2023 to fulfill that need now finds themselves in a position of uncertainty.

Usual suspects - Ubuntu, Debian, Fedora, Suse, Arch. ML practitioners love Ubuntu, Linus loves Fedora.

I would probably use Fedora Desktop as it is closest to AL2023 for laptops.

**Comment by AaronSwearingen** [comment] 2023-08-23 16:12
> I would probably use Fedora Desktop as it is closest to AL2023 for laptops.

ECS Anywhere supports Fedora 33 according to https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html. That's the latest version of Fedora on this list - EOL since 2021-11-30. The rest of the list isn't looking much healthier.

Getting AL2023 on the list would go a long way towards AWS showing it is committed to supporting hybrid cloud.

**Comment by hesaurey** [comment] 2023-08-23 17:14
Amazon please release OVA for Vmware it's good for you, good for us!

**Comment by cpswan** [comment] 2023-08-29 14:06
The Register referenced this issue with their piece [Amazon Linux 2023 virtual machine images still MIA](https://www.theregister.com/2023/08/25/amazon_linux_2023_vm/)

It closes with the usual:

> Amazon did not respond to a request for comment

But let's hope that it helps get some attention onto fixing the problem.

**Comment by Rosch** [comment] 2023-09-12 11:51
Hi Amazon

An on premise version of AL 2023 is truly missing. When will it be available?
We want to fully support AL2023 with our software but developing for it 
is only possible when it is available in our intranet. So yet we can only support AL2.

Beside of helping software developers an on premise version of AL 2023
is really a good chance for AL to fill the gap caused by RHELs actions.

Thanks

Roland

**Comment by hong539** [comment] 2023-10-05 14:27
Hello! Any updates? Thanks!

**Comment by ozbenh** [comment] 2023-10-06 03:51
Unfortunately not yet but we haven't dropped the ball either, stay tuned

**Comment by chris-bragg-sift** [comment] 2023-10-10 08:39
Hello, can this be expedited please, I have multiple existing KVM images that I would like to upgrade to AL2023. Many thanks.

**Comment by ferben** [comment] 2023-10-12 08:10
`   ,     #_
   ~\_  ####_        Amazon Linux 2
  ~~  \_#####\
  ~~     \###|       AL2 End of Life is 2025-06-30.
  ~~       \#/ ___
   ~~       V~' '->
    ~~~         /    A newer version of Amazon Linux is available!
      ~~._.   _/
         _/ _/       Amazon Linux 2023, GA and supported until 2028-03-15.
       _/m/'           https://aws.amazon.com/linux/amazon-linux-2023/`

So I would like upgrade to 2023, really, but there no VM ISO 👎

**Comment by stewartsmith** [comment] 2023-11-16 21:52
Good news everyone!

We have just released the first KVM and VMware images of Amazon Linux 2023.

The documentation is up at https://docs.aws.amazon.com/linux/al2023/ug/outside-ec2.html
and these first images can be found at https://cdn.amazonlinux.com/al2023/os-images/2023.2.20231113.0/ (the https://cdn.amazonlinux.com/al2023/os-images/latest/ URL that is in the User Guide will work shortly, and always lead to the latest release, much like it does for AL2, and I'll update this comment when I've verified it's working).

The documentation covers supported device types and related things.

This version of the images have a few extra development packages installed by default, and we'll make the minor change in an upcoming revision of the images (i.e. AL2023.3) to more closely mirror the package content of the standard AMIs. At that point in time we'll update the docs to show the full package list of the KVM and VMware images (like is present for the [AMIs](https://docs.aws.amazon.com/linux/al2023/ug/image-comparison.html) and [container image](https://docs.aws.amazon.com/linux/al2023/ug/al2023-container-image-types.html) types).

In the meantime, we welcome feedback on these images and documentation on how to use them!

**Closed by stewartsmith** 2023-11-16 21:52 UTC
Labels: enhancement, on-prem

**Comment by Manouchehri** [comment] 2023-11-16 21:53
https://cdn.amazonlinux.com/al2023/os-images/latest/ gives a permission denied.

**Comment by stewartsmith** [comment] 2023-11-16 21:55
> https://cdn.amazonlinux.com/al2023/os-images/latest/ gives a permission denied.

As I noted in my comment, it'll work in a little while, and in the meantime you can grab the first revision of the images at https://cdn.amazonlinux.com/al2023/os-images/2023.2.20231113.0/ .

We're actively working on fixing the `latest` URL.

**Comment by stewartsmith** [comment] 2023-11-16 22:47
FYI, https://cdn.amazonlinux.com/al2023/os-images/latest/ works now.

**Comment by chadbrewbaker** [comment] 2023-11-17 00:08
kvm images are giving 404. How about an aarch64 so I can run with @utmapp natively on my Mac M1?

**Comment by ccassidy-maxar** [comment] 2023-11-17 00:48
Thanks for the update!  Unfortunately when I try to load the ova into VMWare Workstation (17.0.2) I get the following error:
![image](https://github.com/amazonlinux/amazon-linux-2023/assets/47612090/364d6a2e-48f9-477c-b3ae-d6cf3dfa7bc0)

**Comment by ozbenh** [comment] 2023-11-17 01:01
> Thanks for the update! Unfortunately when I try to load the ova into VMWare Workstation (17.0.2) I get the following error: ![image](https://user-images.githubusercontent.com/47612090/283635104-364d6a2e-48f9-477c-b3ae-d6cf3dfa7bc0.png)

That is odd... can you try converting it to vmx+vmdk with ovftool first see if that helps ?

**Comment by ccassidy-maxar** [comment] 2023-11-17 01:28
> > Thanks for the update! Unfortunately when I try to load the ova into VMWare Workstation (17.0.2) I get the following error: ![image](https://user-images.githubusercontent.com/47612090/283635104-364d6a2e-48f9-477c-b3ae-d6cf3dfa7bc0.png)
> 
> That is odd... can you try converting it to vmx+vmdk with ovftool first see if that helps ?

Tried that, and threw a similar error:
``` ./ovftool al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova al2023-ova/
Opening OVA source: al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova
The manifest validates
Opening VMX target: al2023-ova/
Writing VMX file: al2023-ova/al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt/al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.vmx
Transfer Failed
Error: Disk (al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk2.vmdk) could not be found.
Deleting directory tree below: al2023-ova/al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt`
```

I even tried using tar to extract the files (which does show a disk2 file) and reconstructing the ova and it still failed.

```
$ ls 
al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk1.vmdk
al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk2.vmdk
al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.mf
al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ovf

$ ovftool al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ovf al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova
Opening OVF source: al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ovf
The manifest validates
Opening OVA target: al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova
Writing OVA package: al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova
Transfer Failed
Error: Failed to open disk: al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk2.vmdk. Reason: The file specified is not a virtual disk
Completed with errors
```

**Comment by tanvp112** [comment] 2023-11-17 01:29
The links https://cdn.amazonlinux.com/al2023/os-images/latest/ and https://cdn.amazonlinux.com/al2023/os-images/2023.2.20231113.0/ returned 404:

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: os-images/2023.2.20231113.0/index.html
RequestId: PM0PRTE9GCANEGW3
HostId: 33/PHIgJZfTLYzV1NDyrTg3M/Vr4K8rh6jJ5VA+qKkbY9XrnHzGNUxhwj8ohNz9E13gLtfUdExY=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

Wrong path (key)?

**Comment by stewartsmith** [comment] 2023-11-17 02:16
> kvm images are giving 404.

This should have been a temporary issue, I see things are working now.

> How about an aarch64 so I can run with @utmapp natively on my Mac M1?

We have aarch64 KVM images available.

I've booted https://cdn.amazonlinux.com/al2023/os-images/2023.2.20231113.0/kvm-arm64/al2023-kvm-2023.2.20231113.0-kernel-6.1-arm64.xfs.gpt.qcow2 with UTM on a M1 MacBook Pro just fine (I did not test anything really past getting to a `login:` prompt). You will need to enable the serial console, import the disk image, and provide the `seed.iso` (the macOS instructions for generating it that are in the AL2023 documentation worked for me)

Undoubtedly there could be UX improvements here for running cloud like images in UTM; but it does appear to work.

**Comment by stewartsmith** [comment] 2023-11-17 02:18
> The links https://cdn.amazonlinux.com/al2023/os-images/latest/ and https://cdn.amazonlinux.com/al2023/os-images/2023.2.20231113.0/ returned 404:

You possibly hit a temporary issue. Releasing a new image type for a new major version of the OS isn't nearly as frequent as releasing a security update, so we get to discover all of the hiccups in that process. Thanks for understanding, and thanks to the AL team for getting this all going.

**Comment by stewartsmith** [comment] 2023-11-17 02:25
> Undoubtedly there could be UX improvements here for running cloud like images in UTM; but it does appear to work.

I just realized that the drive-resizing UI element that makes this practical was something I worked on a bit back when: https://github.com/utmapp/UTM/pull/4087 - maybe I'll get bored on a weekend again and try and do something for cloud like images.

**Comment by ccassidy-maxar** [comment] 2023-11-17 02:50
Follow up to the issue w/ VMWare Workstation and the disk2 error.  The following method at least allowed me to boot up to a prompt.  Not sure if it will cause any unintended consequences yet.

1. Extract component files from the ova using tar
2. Delete references to the disk2 file from the .ovf file (3 places)
3. Get the SHA512 sum on the updated ovf file
4. Delete the disk2 references from the mf file, and update the ovf checksum
5. Recreated the ova with the following:
`ovftool al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ovf al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova`

Also noticed that the al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk2.vmdk file was actually XML, not sure if that is expected or not.

**Comment by ozbenh** [comment] 2023-11-17 05:14
> Follow up to the issue w/ VMWare Workstation and the disk2 error. The following method at least allowed me to boot up to a prompt. Not sure if it will cause any unintended consequences yet.
> 
> 1. Extract component files from the ova using tar
> 2. Delete references to the disk2 file from the .ovf file (3 places)
> 3. Get the SHA512 sum on the updated ovf file
> 4. Delete the disk2 references from the mf file, and update the ovf checksum
> 5. Recreated the ova with the following:
>    `ovftool al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ovf al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova`
> 
> Also noticed that the al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk2.vmdk file was actually XML, not sure if that is expected or not.

This is very strange.... we built this ova using the same tooling we've always used for AL2 and tested it with both VMware workstation (17.5) and vSphere... I will take a look as soon as I'm not in a plane

**Comment by rotan-hanrahan** [comment] 2023-11-17 12:37
I'm bound to a VirtualBox environment, and have used the VB images from Amazon ( such as here https://cdn.amazonlinux.com/os-images/2.0.20231101.0/ ), so I guess I will wait while the bugs are ironed out of the kvm/vmware versions and see what happens. So glad to see movement on this again, though I did lose one client to the "dark side" on account of no offsite pre-deployment options like we had with the previous images. (I might try to pull them back if the VB image appears.)

I'll take a quick peek once the URLs stop returning 404s.

Thanks @stewartsmith.

**Comment by sn-tm** [comment] 2023-11-17 14:38
I'm experiencing the same issue as @ccassidy-maxar. VMWare Workstation Pro 17.5.0 on Windows 11. Open the .ova, give the VM a name and path, then see the same error, "Disk (al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt-disk2.vmdk) could not be found."

I retested the same procedure using the AL2 .ova and had no problems.

By the way, thanks for providing this image. This is what we've been waiting for to help us test our software and migrate to AL2023 (once we resolve this issue of course!)

**Comment by ozbenh** [comment] 2023-11-17 16:54
So it does look like the al2023 OVA has two "disks" in it, while previously we had only one. Probably due to its size (which incidently will be reduced in the next release as @stewartsmith mentioned).

I wonder if there's a host type related issue here. What are you using (both the good and base cases) ? We do our testing on a Ubuntu 22.04.3 system with VMWare Workstation for Linux, could it be a Windows specific issue ?

**Comment by sn-tm** [comment] 2023-11-17 17:20
Hi @ozbenh, I just tried this on Ubuntu 22.04.3. Downloaded and installed VMWare Workstation 17 Pro, opened `al2023-vmware_esx-2023.2.20231113.0-kernel-6.1-x86_64.xfs.gpt.ova`, entered a name and location, clicked Import.

![image](https://github.com/amazonlinux/amazon-linux-2023/assets/103436289/a1105126-4305-471c-8ac2-9c57b08f43d4)

**Comment by ozbenh** [comment] 2023-11-17 17:35
Ok, something's wrong on our end with the testing :-( We'll get to the bottom of it asap

**Comment by ozbenh** [comment] 2023-11-17 20:56
We found the cause of the issue and will be updating the images. A sad story involving different versions of `open-vmdk` having different (incompatible) syntax for `mkova.sh` ... ugh. It should have been caught, sorry about that, something slipped in the test validation. Stay tuned for updated images. We'll also be slimming them a bit as mentioned earlier by @stewartsmith

**Comment by ozbenh** [comment] 2023-11-18 01:34
A fixed (and slimmed) OVA has been uploaded and replaces the previous one. We haven't changed the KVM ones at all for now

**Comment by ccassidy-maxar** [comment] 2023-11-18 02:34
> A fixed (and slimmed) OVA has been uploaded and replaces the previous one. We haven't changed the KVM ones at all for now

Tested the new OVA and worked flawlessly on VMWare Workstation 17.0.2 / Windows 10, thanks!

**Comment by tanvp112** [comment] 2023-11-18 04:18
> I'm bound to a VirtualBox environment, and have used the VB images from Amazon ( such as here https://cdn.amazonlinux.com/os-images/2.0.20231101.0/ ), so I guess I will wait while the bugs are ironed out of the kvm/vmware versions and see what happens. So glad to see movement on this again, though I did lose one client to the "dark side" on account of no offsite pre-deployment options like we had with the previous images. (I might try to pull them back if the VB image appears.)
> 
> I'll take a quick peek once the URLs stop returning 404s.
> 
> Thanks @stewartsmith.

The OVA can be imported into VB 6.1.48, but after change password there seems to be storage driver incompatibility; either the new password is not recognized or error with "Authentication token manipulation". Will need to upgrade to v7.x and tune the seed file.

**Comment by ozbenh** [comment] 2023-11-18 04:39
> > I'm bound to a VirtualBox environment, and have used the VB images from Amazon ( such as here https://cdn.amazonlinux.com/os-images/2.0.20231101.0/ ), so I guess I will wait while the bugs are ironed out of the kvm/vmware versions and see what happens. So glad to see movement on this again, though I did lose one client to the "dark side" on account of no offsite pre-deployment options like we had with the previous images. (I might try to pull them back if the VB image appears.)
> > I'll take a quick peek once the URLs stop returning 404s.
> > Thanks @stewartsmith.
> 
> The OVA can be imported into VB 6.1.48, but after change password there seems to be storage driver incompatibility; either the new password is not recognized upon reboot or error with "Authentication token manipulation". Will need to try 7.x and possibly tune the seed files...

VirtualBox has been .... weird ... can you try converting the image away from vmdk to vdi (I suppose there's a way to do that, I haven't researched) first ? I would not be surprised if VB has bugs around vmdk handling...

**Comment by tanvp112** [comment] 2023-11-18 05:06
The VMDK formatted hard drive has no issue convert into VDI. Previously for AL2, [a VB image is provided by AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html#amazon-linux-2-virtual-machine-download) and it works out of the box. Believe it or not, I have run this copy & still running today for >5 years day-in-day-out. AL2 is arguably the best Linux experience I ever had so far.

The release of AL2023 image is a big step to many... _kudos_ for AWS Linux team. Hopefully, there will be a VB image like the former and the superb experience would continue. For the case above, VB 6.1.x is sunsetting already, will need to test with latest VB 7.x instead.

Happy to hear more about others' experience using VB with the new image!

**Comment by yoonjs2** [comment] 2023-11-18 06:17
Is possible to convert AL2023 arm64 qcow2 to parallels hdd format? I'm bounded to macOS with apple silicon environment and uses parallels in dev/production.

**Comment by ozbenh** [comment] 2023-11-18 19:11
> Is possible to convert AL2023 arm64 qcow2 to parallels hdd format? I'm bounded to macOS with apple silicon environment and uses parallels in dev/production.

I don't have a Mac to try (though @stewartsmith does, he might come up with an answer), but Google has a few hits on this. Alternatively there's a qemu for Mac which uses Hypervisor Framework under the hood and there's UTM as a front-end for it all

**Comment by ozbenh** [comment] 2023-11-22 16:21
> > Is possible to convert AL2023 arm64 qcow2 to parallels hdd format? I'm bounded to macOS with apple silicon environment and uses parallels in dev/production.
> 
> I don't have a Mac to try (though @stewartsmith does, he might come up with an answer), but Google has a few hits on this. Alternatively there's a qemu for Mac which uses Hypervisor Framework under the hood and there's UTM as a front-end for it all

I did some experimentations and it didn't go particularly well. Not only converting to parallel is tricky and messy (the tools don't work well and parallels itself doesn't seem to be helping), but the end result doesn't boot.

I think I know why (they and vmware fusion both seem to be exposing storage as some kind of ACPI generated platform AHCI that isn't PCI backed, and we don't enable that driver). I'll see if I can get that turned on in a future kernel release. That said, we don't have plans at this stage to produce officially supported Parallels images.

**Comment by michailf** [comment] 2023-11-24 23:46
Does anyone have a reference to login information?  What user and password would I use for the images downloaded from the links provided?

**Comment by azN2** [comment] 2023-11-25 00:08
> Does anyone have a reference to login information?  What user and password would I use for the images downloaded from the links provided?

Cloud-init

**Comment by stewartsmith** [comment] 2023-11-25 00:30
> Does anyone have a reference to login information? What user and password would I use for the images downloaded from the links provided?

Be sure to read the instructions on https://docs.aws.amazon.com/linux/al2023/ug/outside-ec2.html for configuring the VM. There isn't a password set, you need to set up something so that `cloud-init` can configure the instance on first boot.

**Comment by michailf** [comment] 2023-11-25 05:58
I spent hours trying to figure out how to login to the provided image.  I have read multiple documents, including the reference here.  I cannot log in to the image.  I was able to set the local hostname via the meta-data (guestinfo.metadata) so I believe I provide the data correctly.  What I do not know is why the users are not being setup with a simple password.

Is there a working example of the user-data (guestinfo.userdata) that allows a simple password log in with sudo rights to the image provided?

**Comment by michailf** [comment] 2023-11-25 06:59
I was able to log in using an ssh key.  I then could create/adjust other users to my needs.  It seems the cloud-init in the image does not allow for plain passwords.

**Comment by tanvp112** [comment] 2023-11-25 07:23
> I think I know why (they and vmware fusion both seem to be exposing storage as some kind of ACPI generated platform AHCI that isn't PCI backed, and we don't enable that driver).

This really rings a bell! I suspect this is required for the image to be compatible for VB as well.

**Comment by gebailey** [comment] 2023-11-26 00:57
> The VMDK formatted hard drive has no issue convert into VDI. Previously for AL2, [a VB image is provided by AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html#amazon-linux-2-virtual-machine-download) and it works out of the box. 

I've built Vagrant cloud images (virtualbox provider) of Amazon Linux 2 for a few years now, and just uploaded one for Amazon Linux 2023 that was built from the VMware OVA. A few steps were required to convert from OVA->VMDK->VDI but seems to work just fine.  https://app.vagrantup.com/gbailey/boxes/al2023

**Comment by michailf** [comment] 2023-11-28 12:47
> I have used images with passwords a few times but usually by creating a new user, something like:
> 
> ```
>   - name: benh
>     groups: sudo
>     sudo: ['ALL=(ALL) NOPASSWD:ALL']
>     ssh-authorized-keys:
>       - <key>
>     plain_text_passwd: <password>
>     lock_passwd: false
> ```

I got `ssh-authorized-keys` to work but not `plain_text_passwd` independently.  I have not tried both of the options for the same user.

> This doesn't seem to work with `ec2-user` last I tried, but did you check if the old-school `chpasswd` method works ? From the AL2 on-prem docs:
> 
> ```
> chpasswd:
>   list: |
>     ec2-user:<plain_text_password>
> ```

I also tried the `chpasswd` method but it did not work for me.

**Comment by ozbenh** [comment] 2023-11-29 02:07
I just tested again with
```
#cloud-config
#vim:syntax=yaml
users:
  - name: test
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    plain_text_passwd: passw0rd
    lock_passwd: false
```
and it worked fine

Are you logging in via the console or serial ? Or are you trying to ssh ? Passsword authentication is disabled in the ssh server by default.

**Comment by nileshtrivedi** [comment] 2024-08-27 08:23
Is there a tutorial somewhere for running AL2023 on Apple M1 machines (perhaps via UTM)?

**Comment by ozbenh** [comment] 2024-08-28 23:27
I did run for fun and no profit our qcow2 image on an M1 mac using UTM a while back, though I don't remember the details. It's not a tested/supported solution so we don't have official docs, but I can try to snatch my partner's M1 one of these days and try again & let you know

**Comment by nileshtrivedi** [comment] 2024-08-29 03:29
@ozbenh Actually I got it working with some effort. This is the `user-data` file that went into seed.iso attached as a CDROM in the UTM machine:

```
#cloud-config
#vim:syntax=yaml
password: test123
chpasswd:
  expire: False

users:
  - default
  - name: ec2-user
    lock_passwd: false
    plain_text_passwd: test123
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 yourkey_goes_here
```

It help to delete the .qcow2 and .iso disks fully and add again after every change.

**Comment by yoonjs2** [comment] 2024-08-29 03:37
For people looking for the al2023 vagrant box + apple silicon + parallels, I created and uploaded working box here: https://portal.cloud.hashicorp.com/services/vagrant/registries/hbsmith/boxes/al2023

I created the box using conversions on the mac like this: qemu qcow2 -> vmware vmdk -> parallels hdd then pack it into pvm & vagrant box. AL2023 has no problem with installing parallels tools extension and work with vagrant like a charm. (except manually assign fixed ip to network interface.)

Hope it helps.

**Comment by ozbenh** [comment] 2024-08-29 06:45
Ah I was about to update here but you beat me to it :-) Yes, our ARM64 image seems to work with UTM and the default "virt" machine type (I think it's 7.2) on an M1. As for seed.iso , well ... that's documented in various places :-)

The one thing that I noticed doesn't work is Secure Boot as you can't enroll our keys, the problem seems to be that UTM comes up pre-provisioned with its own set of keys instead of in Setup Mode. It might be worth filing a feature request for that.  We don't currently provide a pre-made UEFI variables blob in qemu format but you can use python3-virt-firmware or python-uefivars to convert ours from AWS format to Qemu format (you can find our blob and our keys in `/usr/share/amazon-linux-sb-keys/`, the UEFI variables blob is `uefi.vars`.

It would be nice if UTM provided AL2023 in their Gallery I suppose ...
