### ISSUE TITLE
[Package Request] - php-memcached

### ISSUE THREAD

**Issue by LhyanGRoblesR** [amazonlinux/amazon-linux-2023#536] opened 2023-11-02 14:38 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
php-memcached - php connector for memcached

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
No, but it is available through EPEL.

**Any additional information you'd like to include. (use-cases, etc)**
php-memcached through EPEL was unavailable for a while due to problems with their web site, which caused problems for those of us who used it.

**Comment by trondude** [comment] 2023-11-07 23:10
We need this asap. Can't use our Elasticache / memcached cluster with out it so we can't upgrade to Amazon Linux 2023 until this works.

**Comment by stewartsmith** [comment] 2023-11-08 17:25
I'm guessing you're meaning the PECL module https://src.fedoraproject.org/rpms/php-pecl-memcached which is in EPEL7.

**Comment by LhyanGRoblesR** [comment] 2023-11-10 01:58
It seems to be the same one that PHP recommends us [https://pecl.php.net/package/memcached](https://pecl.php.net/package/memcached) , anyway relying on a third party is not what is required, it was reliable for a while until recently that presented a problem with your website, which disabled my servers when trying to access the cache.

**Comment by limmike** [comment] 2023-11-11 13:11
> Can't use our Elasticache / memcached cluster with out it so we can't upgrade to Amazon Linux 2023 until this works.

You can install php-memcached on AL2023 via PECL as per #208

Another option is  [AL2023 CloudFormation template](https://github.com/aws-samples/ec2-lamp-server) that includes common PHP extensions include php-memcache and php-redis.

**Comment by stewartsmith** [comment] 2023-11-11 17:09
Thanks for pointing out #208 , which this is a duplicate of. So, I'll move everything over to track in #208 .

**Closed by stewartsmith** 2023-11-11 17:09 UTC
Labels: enhancement, packages, epel
