### ISSUE TITLE
Chromium and Chromedriver rpm support

### ISSUE THREAD

**Issue by dnyanec** [amazonlinux/amazon-linux-2023#543] opened 2023-11-07 14:30 UTC
We, at NetScout, as part of our nGeniusONE reporting product use below rpms for spawning a headless browser on server side to support our scheduled report email delivery functionality.

chromium
chromium-common
chromedriver

Recently, one of our customer who is using Amazon Linux 2023 has requested support for this operating system. As part of supporting this operating system, we need to install the above rpms as part of our nGeniusONE product. Kindly provide support for the above rpms. Please let me know if you need any other details.

Thanks,
Chetan Valmik Dnyane,
Principal Software Engineer II,
NetScout Systems

**Comment by stewartsmith** [comment] 2023-11-08 17:30
Chromium isn't particularly friendly to being packaged by Linux distributions (source: the person who does it for Fedora works for AWS), does https://www.chromium.org/getting-involved/download-chromium/ work for your use case?

**Comment by stewartsmith** [comment] 2024-02-08 04:00
There is also Chromium available via flatpak, which appears to work pretty well on AL2023

**Comment by dnyanec** [comment] 2024-02-08 04:05
Hi Stewart,

Thanks for your suggestion. We need below three rpms. Is there any possibility that Amazon Linux 2023 might support these in the near future. Please suggest

chromium
chromium-common
chromedriver

Thanks,
Chetan

**Comment by stewartsmith** [comment] 2024-05-15 17:21
I'm going to mark this as a duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/356 but add comments about chromedriver.

**Closed by stewartsmith** 2024-05-15 17:21 UTC
Labels: duplicate, enhancement, packages
