### ISSUE TITLE
[Package Request] - Varnish Cache

### ISSUE THREAD

**Issue by dieguitoqueiroz** [amazonlinux/amazon-linux-2023#521] opened 2023-10-19 13:13 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Varnish
https://varnish-cache.org/
**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes. EPEL.

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by stewartsmith** [comment] 2023-10-20 02:32
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/406 thus will resolve this issue and track on the existing one.

**Closed by stewartsmith** 2023-10-20 02:32 UTC
Labels: duplicate
