### ISSUE TITLE
[Package Request] - libxcrypt-compat

### ISSUE THREAD

**Issue by saieva** [amazonlinux/amazon-linux-2023#182] opened 2022-09-01 19:40 UTC
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`libxcrypt-compat`

**Is this an update to existing package or new package request?**
New package install request, needed for Chef (https://www.Chef.io). Without this package installed the chef-run command produces the following error:

```
[2022-09-01T14:27:44-04:00] ERROR: stderr: /opt/chef/embedded/bin/ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

The `libxcrypt-compat` package should be pre-installed by default so chef-run can be used to bootstrap an EC2 instance running Amazon Linux 2022 without requiring the system to be pre-configured to run Chef.

**Is this package available in Amazon Linux 2?**
Not used on Amazon Linux 2.

**Number of users impacted**
All users of Amazon Linux 2022.

**Comment by ozbenh** [comment] 2023-09-21 00:44
This is caused by `chef` trying to run a pre-built binary (ruby interpreter no less) that was built for another distribution. This usage pattern isn't supported for AL2023.

What is needed is for the ISV to provide an officially supported version of `chef` for AL2023. Tentatively closing this as we aren't going to add this old package.

**Closed by ozbenh** 2023-09-21 00:44 UTC
Labels: enhancement

**Comment by thimslugga** [comment] 2024-03-20 18:59
Related to https://github.com/chef/chef/issues/13572
