### ISSUE TITLE
[Bug] - Installation of CodeDeploy agent fails

### ISSUE THREAD

**Issue by herrsergio** [amazonlinux/amazon-linux-2023#277] opened 2023-03-02 22:44 UTC
**Describe the bug**
Following the instructions of installing the CodeDeploy agent (https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-linux.html).
The installation fails with the following error message:
```
/usr/share/ruby3.2/logger/log_device.rb:83:in `exist?': no implicit conversion of Array into String (TypeError)

          if File.exist?(path)
                         ^^^^
	from /usr/share/ruby3.2/logger/log_device.rb:83:in `set_dev'
	from /usr/share/ruby3.2/logger/log_device.rb:18:in `initialize'
	from /usr/share/ruby3.2/logger.rb:587:in `new'
	from /usr/share/ruby3.2/logger.rb:587:in `initialize'
	from ./install:43:in `new'
	from ./install:43:in `<main>'

```
**To Reproduce**
1. `dnf install ruby`
2. `curl -k https://aws-codedeploy-us-west-2.s3.amazonaws.com/latest/install -o install`
3. `chmod +x install`
4. `./install`

**Expected behavior**
Installation of needed files for the CodeDeploy agent.

**Additional context**
```
ruby3.2-libs-3.2.0-177.amzn2023.0.1.x86_64
ruby3.2-rubygem-json-2.6.3-177.amzn2023.0.1.x86_64
ruby3.2-rubygem-io-console-0.6.0-177.amzn2023.0.1.x86_64
ruby3.2-3.2.0-177.amzn2023.0.1.x86_64
ruby3.2-rubygem-bigdecimal-3.1.3-177.amzn2023.0.1.x86_64
ruby3.2-rubygem-bundler-2.4.1-177.amzn2023.0.1.noarch
ruby3.2-rubygem-psych-5.0.1-177.amzn2023.0.1.x86_64
ruby3.2-default-gems-3.2.0-177.amzn2023.0.1.noarch
ruby3.2-rubygems-3.4.1-177.amzn2023.0.1.noarch
ruby3.2-rubygem-rdoc-6.5.0-177.amzn2023.0.1.noarch
```

```
# cat /etc/system-release
Amazon Linux release 2023 (Amazon Linux)
```

**Comment by netsnipe** [comment] 2023-03-03 04:43
Duplicate of aws/aws-codedeploy-agent#301

**Comment by herrsergio** [comment] 2023-03-03 14:41
I would say this is a big blocker for AL2023 to be GA.

**Comment by stewartsmith** [comment] 2023-03-03 15:22
I'll check in with the CodeDeploy team today and see what can be done to get the agent packaged for Amazon Linux.

I am not viewing this as a GA blocker for AL2023, but do understand it can be a migration blocker for yourselves and all CodeDeploy customers.

**Comment by herrsergio** [comment] 2023-03-10 20:52
The new CodeDeploy agent version 1.5.0, which adds support to Ruby 3, is also not working in AL2023.
https://github.com/aws/aws-codedeploy-agent/issues/351

**Comment by nmeyerhans** [comment] 2023-04-20 17:07
The CodeDeploy team has released a new version that adds AL2023 support. Details in https://github.com/aws/aws-codedeploy-agent/issues/360

**Closed by nmeyerhans** 2023-04-20 17:07 UTC
Labels: bug, aws-integration
