### ISSUE TITLE
[Package Request] - php-pecl-imagick

### ISSUE THREAD

**Issue by sharuzzaman** [amazonlinux/amazon-linux-2023#596] opened 2024-01-01 12:49 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**

php-pecl-imagick 

Description from Fedora package repo: Imagick is a native php extension to create and modify images using the ImageMagick API. 

Ref: https://packages.fedoraproject.org/pkgs/php-pecl-imagick/php-pecl-imagick/

**Is this an update to existing package or new package request?**

New package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

Yes, and from the Fedora distribution

**Any additional information you'd like to include. (use-cases, etc)**

There are previous request at issue #466 but was closed because the requester is comfortable with manually building and installing the library. Most people are not comfortable of compiling their own binary, or are technically capable of doing it.

Also, it is common for user of Linux distro is to maintain as much packages provided by the OS vendor, rather than building manually. It is also ensure repeatability when creating new instances.

It provides a PHP module that is highly recommended for a [WordPress installation](https://make.wordpress.org/hosting/handbook/server-environment/#php-extensions), as well as providing a host of image manipulation facilities.

My customer is using Imagick function in his PHP code, and thus require this packages.

Please include this package because for people moving over from Amazon Linux 2 (RHEL 7 compatible) to more up to date OS, this package is so common among PHP developer that is unthinkable to not include it in as default.

All other Linux distro included this package by default.

Debian:
Package php-imagick

    [buster (oldoldstable)](https://packages.debian.org/buster/php-imagick) (php): Provides a wrapper to the ImageMagick library
    3.4.3-4.1: amd64 arm64 armel armhf i386 mips mips64el mipsel ppc64el s390x
    [bullseye (oldstable)](https://packages.debian.org/bullseye/php-imagick) (php): Provides a wrapper to the ImageMagick library
    3.4.4+php8.0+3.4.4-2+deb11u2: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x
    [bookworm (stable)](https://packages.debian.org/bookworm/php-imagick) (php): Provides a wrapper to the ImageMagick library
    3.7.0-4: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x
    also provided by: [php8.2-imagick](https://packages.debian.org/bookworm/php8.2-imagick)
    [trixie (testing)](https://packages.debian.org/trixie/php-imagick) (php): Provides a wrapper to the ImageMagick library
    3.7.0-4+b1: amd64 arm64 armel armhf i386 mips64el ppc64el s390x
    also provided by: [php8.2-imagick](https://packages.debian.org/trixie/php8.2-imagick)
    [sid (unstable)](https://packages.debian.org/sid/php-imagick) (php): Provides a wrapper to the ImageMagick library
    3.7.0-4+b1: alpha amd64 arm64 armel armhf hppa i386 ia64 m68k mips64el ppc64 ppc64el riscv64 s390x sparc64 x32
    3.7.0-2 [[debports](https://www.ports.debian.org/)]: sh4
    also provided by: [php8.1-imagick](https://packages.debian.org/sid/php8.1-imagick), [php8.2-imagick](https://packages.debian.org/sid/php8.2-imagick)

Ubuntu:
Package php-imagick

    [focal (20.04LTS)](https://packages.ubuntu.com/focal/php-imagick) (php): Provides a wrapper to the ImageMagick library [universe]
    3.4.4-4: amd64 arm64 armhf ppc64el s390x
    [jammy (22.04LTS)](https://packages.ubuntu.com/jammy/php-imagick) (php): Provides a wrapper to the ImageMagick library [universe]
    3.6.0-4ubuntu1: amd64 arm64 armhf ppc64el riscv64 s390x
    also provided by: [php8.1-imagick](https://packages.ubuntu.com/jammy/php8.1-imagick)
    [lunar (23.04)](https://packages.ubuntu.com/lunar/php-imagick) (php): Provides a wrapper to the ImageMagick library [universe]
    3.7.0-4: amd64 arm64 armhf ppc64el riscv64 s390x
    also provided by: [php8.1-imagick](https://packages.ubuntu.com/lunar/php8.1-imagick)
    [mantic (23.10)](https://packages.ubuntu.com/mantic/php-imagick) (php): Provides a wrapper to the ImageMagick library [universe]
    3.7.0-4build2: amd64 arm64 armhf ppc64el riscv64 s390x
    also provided by: [php8.2-imagick](https://packages.ubuntu.com/mantic/php8.2-imagick)
    [noble](https://packages.ubuntu.com/noble/php-imagick) (php): Provides a wrapper to the ImageMagick library [universe]
    3.7.0-4build2: amd64 arm64 armhf ppc64el riscv64 s390x
    also provided by: [php8.2-imagick](https://packages.ubuntu.com/noble/php8.2-imagick)

All other distro:
Ref: https://pkgs.org/search/?q=imagick

**Comment by stewartsmith** [comment] 2024-01-11 16:22
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/207

**Closed by stewartsmith** 2024-01-11 16:22 UTC
