### ISSUE TITLE
[Package Request] - xmlstarlet

### ISSUE THREAD

**Issue by saste** [amazonlinux/amazon-linux-2023#458] opened 2023-09-21 09:07 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
Xmlstarlet

Website: https://xmlstar.sourceforge.net/source.php

This utility is useful to process XML content.

**Is this an update to existing package or new package request?**

This is a new package request.

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

It was missing in AL2 but it could be included via EPEL.

**Any additional information you'd like to include. (use-cases, etc)**

This is especially useful together with tools using XML for configuration. Currently the most convenient way to include it in AL2023 is by building. Having a pre-compiled package would simplify deployment.

I have an use case where xmlstarlet is used by an installer, missing xmlstarlet will break the installer.

**Comment by saste** [comment] 2023-09-21 10:35
For convenience, I'm putting here the commands needed to install from scratch:
```
yum groupinstall -y "Development 
yum install -y git libxml2-devel libxslt-devel docbook-xsl docbook-dtds
rm -rf xmlstar
git clone git://xmlstar.git.sourceforge.net/gitroot/xmlstar/xmlstar    
(
        cd xmlstar
        autoreconf -sif
        ./configure --with-libxml-prefix=/usr --with-libxslt-prefix=/usr --prefix /usr
        make
        make install
        ln -sf /usr/bin/xml /usr/bin/xmlstarlet
)
```

Note that a link is created to xmlstarlet (since xmlstarlet is the name used e.g. in the xmlstarlet epel package).

**Comment by stewartsmith** [comment] 2024-07-24 01:49
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/550

https://github.com/amazonlinux/amazon-linux-2023/issues/550#issuecomment-1820437601 details how the upstream project is effectively unmaintained.

**Closed by stewartsmith** 2024-07-24 01:49 UTC
Labels: enhancement, packages, epel
