### ISSUE TITLE
[Package Request] - php-zip

### ISSUE THREAD

**Issue by tsumura-akihiro** [amazonlinux/amazon-linux-2023#382] opened 2023-06-20 14:18 UTC
Please make sure that "php-zip" can be handled by yum in Amazon Linux 2023

**Comment by stewartsmith** [comment] 2023-06-22 21:16
This is a duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/195

**Closed by stewartsmith** 2023-06-22 21:16 UTC
