### ISSUE TITLE
[Package Request] - MOD_WSGI

### ISSUE THREAD

**Issue by tickerBerkin** [amazonlinux/amazon-linux-2023#532] opened 2023-10-27 10:42 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
[python3-]mod_wsgi - A WSGI interface for Python web applications in Apache

**Is this an update to existing package or new package request?**
New Package request

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Not sure if available on AL2
URL          : https://modwsgi.readthedocs.io/

**Any additional information you'd like to include. (use-cases, etc)**
I realise that this can built with PIP, but needs development environments for Apache, Python and gcc
and the result is more complicated to set up in Apache

**Comment by stewartsmith** [comment] 2023-11-08 17:19
As per https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL2.html this was in AL2 but is not currently in AL2023.

Looking at package download statistics, it does have a *very* low number of downloads from AL2 though.

If added to AL2023, is the RPM packaging of it going to be valuable and used?

**Comment by ecofor** [comment] 2024-04-12 14:48
I was also interested, tried other WSGI interfaces with no much success, so please consider this module, thank you!!

**Comment by Gonsaave** [comment] 2024-04-12 19:24
I'm also interested in this package, leaving a comment here to support the idea of including it.

**Comment by sahilradotra** [comment] 2024-07-10 06:51
We have a requirement from users for the same package. As the deadline for migration is June 2025, encountering similar issues will make it difficult to migrate applications from AL2 to AL2023 within that timeframe.

Kindly let us know if it is still in your plan to add the package mod_wsgi, or if there will be any alternative for the same on AL2023.

**Comment by daniejstriata** [comment] 2024-07-10 10:25
it is building in COPR without any missing dependencies or modification. I built the Centos-Stream version (4.7.1-11) here:
https://copr.fedorainfracloud.org/coprs/faramirza/al2023/build/7722143/

**Comment by stewartsmith** [comment] 2024-07-24 23:48
I'm going to close this issue as a duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/267 so we can track `mod_wsgi` in one place.

**Closed by stewartsmith** 2024-07-24 23:48 UTC
Labels: enhancement, packages
