### ISSUE TITLE
[Package Request] - pcp

### ISSUE THREAD

**Issue by kelleraa** [amazonlinux/amazon-linux-2023#205] opened 2022-10-11 23:34 UTC
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

`pcp`

> Performance Co-Pilot (PCP) provides a framework and services to support
system-level performance monitoring and performance management.

> The PCP open source release provides a unifying abstraction for all of
the interesting performance data in a system, and allows client
applications to easily retrieve and process any subset of that data.

**Is this an update to existing package or new package request?**

New package request.

**Is this package available in Amazon Linux 2?**

`pcp` is included in AL2, but the version is too old to be used with [grafana-pcp](https://github.com/performancecopilot/grafana-pcp), which is the thing I care about using.

`pcp` was previously included in AL2022, but was removed sometime earlier this year.

**Number of users impacted**

Unknown. I have no current deployed use of `pcp` and I don't intend to use it in production, so I don't think I count as an impacted user.

**Comment by stewartsmith** [comment] 2024-05-20 17:14
Actually, this is a duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/105 - so resolving this issue and we'll track the addition of `pcp` there.

**Closed by stewartsmith** 2024-05-20 17:14 UTC
Labels: enhancement, packages
