### ISSUE TITLE
[Package Request] - sg3_utils

### ISSUE THREAD

**Issue by ntap-dans** [amazonlinux/amazon-linux-2023#769] opened 2024-08-01 18:04 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
sg3_utils

**Is this an update to existing package or new package request?**
New Package

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
It is available in AL2. Unsure if it is available via external sources.

**Any additional information you'd like to include. (use-cases, etc)**
This request is on behalf of customers wanting to leverage AL2023 and Astra Trident: https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html#install-the-iscsi-tools 

Duplicate entry found here: https://github.com/amazonlinux/amazon-linux-2023/issues/663

**Comment by ozbenh** [comment] 2024-08-09 03:40
Duplicate of #663

**Closed by ozbenh** 2024-08-09 03:40 UTC
