### ISSUE TITLE
[Package Request] - PHP 8.3

### ISSUE THREAD

**Issue by aran112000** [amazonlinux/amazon-linux-2023#573] opened 2023-12-12 17:46 UTC
**What package is missing from Amazon Linux 2023? Please describe and include package name.**
PHP 8.3

**Is this an update to existing package or new package request?**
The latest stable PHP release, currently only PHP 8.1 and PHP 8.2 are there

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**
Yes

**Comment by RavianXReaver** [comment] 2024-01-11 00:34
When can we expect PHP 8.3 to be added?

**Comment by kivengh** [comment] 2024-02-06 16:09
PHP 8.3 is a requirement, do you know when can we expect a release ?

**Comment by beeradmoore** [comment] 2024-03-06 00:49
I thought 8.2 was out of support but I was wrong.

8.1 is out of active support, has security support until Nov 2024.
8.2 has active support until Dec 2024, security support until Dec 2025.
8.3 has active support until Nov 2025, and security support until Nov 2026.

Looking forward to moving to 8.3. Still checking for it each time there is a new AL2023 AMI out 😅

**Comment by beephotography** [comment] 2024-03-13 12:31
Any news on that?? PHP 8.3 was released 4 moths (!) ago and still no package available?

**Comment by willyk** [comment] 2024-03-14 08:41
Please can you tell us when it will be on Amazon Linux 2023?

**Comment by adelkedjour** [comment] 2024-03-17 20:31
Any news? I think using Amazon Linux was huge mistake as we have to relay on you and all the time we have to request necessary packages that should not removed from the first place.

**Comment by beeradmoore** [comment] 2024-03-17 21:51
> I think using Amazon Linux was huge mistake as we have to relay on you and all the time we have to request necessary packages that should not be removed from the first place.

But you don’t have to rely on them though. You can compile it yourself and distribute it to your own systems if it’s a thing you _need_ today.

**Comment by adelkedjour** [comment] 2024-03-17 22:02
> > I think using Amazon Linux was huge mistake as we have to relay on you and all the time we have to request necessary packages that should not be removed from the first place.
> 
> But you don’t have to rely on them though. You can compile it yourself and distribute it to your own systems if it’s a thing you _need_ today.

That's true, but the problem is that some necessary libraries to build PHP from source might be missing as well from the package repositories. This can complicate the process and may require additional effort to resolve dependencies and ensure a successful build.

**Comment by beeradmoore** [comment] 2024-03-17 22:46
I agree it's not ideal, but it shouldn't be deal breaker. We get around most of these issues by using AWS Image Builder so we can have AMIs that have the things ready to go.

**Comment by adelkedjour** [comment] 2024-03-17 23:07
> I agree it's not ideal, but it shouldn't be deal breaker. We get around most of these issues by using AWS Image Builder so we can have AMIs that have the things ready to go.

Honestly, we use it at work but if it was my decision I will never use AL as OS not even for development.

**Comment by RavianXReaver** [comment] 2024-03-18 05:39
> I think using Amazon Linux was huge mistake as we have to relay on you and all the time we have to request necessary packages that should not be removed from the first place.

I wholeheartedly agree. 
PHP 8.4 will be released on this November 21st. Guess we will have to wait until then?

This was a mistake but it is what it is. Will definetely move away from this distro as the team behind this is unable to deliver.

**Comment by lloricode** [comment] 2024-03-25 06:31
+1

**Comment by willyk** [comment] 2024-03-25 14:00
+1

**Comment by SelimSalihovic** [comment] 2024-04-15 11:36
👍

**Comment by kangwonchul** [comment] 2024-04-19 00:33
+1

**Comment by drupol** [comment] 2024-04-22 13:25
Hi all,

To use any version of PHP on your Amazon Linux, you can use a universal package manager like [Nix](https://nixos.org/).

Once installed, you can create a shell containing PHP 8.3 by doing: `nix shell nixpkgs#php83`

Hope this will help!

**Comment by beephotography** [comment] 2024-05-14 07:46
Asking again: any news on that? It's 6 months (half a year) now that PHP 8.3 was released, that's crazy... when can we expect this version to be released? I mean... will PHP 8.4 be released before PHP 8.3 on Amazon Linux? 😭

**Comment by drupol** [comment] 2024-05-14 07:49
@beephotography, I've shared a potential solution above that we use daily without any issues.

@olmstd and you, could you please share your concerns about this proposal? Your feedback would be valuable to me.

**Comment by adelkedjour** [comment] 2024-05-14 08:48
> @beephotography, I've shared a potential solution above that we use daily without any issues.
> 
> @olmstd and you, could you please share your concerns about this proposal? Your feedback would be valuable to me.

The proposed solution lacks reliability for production environments. Any Linux distribution intended for servers should ideally provide all essential packages and libraries through its official repositories. It's concerning that additional package management tools like Nix are required to install common software such as PHP on AL2023.

This approach feels precarious and introduces unnecessary risk. Instead, I advocate for a more robust solution. At my workplace, I advocated for and implemented the decision to move away from Amazon Linux entirely. We opted to replace it with either Ubuntu or our custom image, which offers greater stability, compatibility, and control over our server environment.

**Comment by peigongdsd** [comment] 2024-05-14 09:37
I don't assume there's a better standalone PM than nix. However, If you really do not want this trouble, just install from source or some out_of_tree.tar.xz is considerable.

**Comment by troy-rudolph** [comment] 2024-06-05 17:26
Please add PHP 8.3 to Amazon Linux 2023.  It has been available since November 2023.  Thank you!

https://www.php.net/supported-versions.php

**Comment by dominic-lear** [comment] 2024-06-10 07:13
I'd also like to request php 8.3 to be made available. In lieu of that it would be great to get clarity on when is planned to become available and then to get visibility into when php 8.4 support will be added once its released November 21, 2024. 

Newer versions of php are required to ensure we stay on the latest versions of Laravel and associated packages from Spatie etc.

**Comment by vovarpd** [comment] 2024-06-13 06:13
Yes, it would be nice to have PHP 8.3.

**Comment by kingIZZZY** [comment] 2024-06-25 18:57
Yes please add PHP 8.3 to amazon linux 2023

**Comment by beeradmoore** [comment] 2024-06-25 23:26
php8.3 was just added to 2023.5.20240624.

**Comment by countless-integers** [comment] 2024-06-26 15:00
Does anyone know if there's a roadmap for PHP updates in the future? [Not for end of support](https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html), but rather for when to expect new versions dropping, so that we can plan upgrades accordingly.

**Comment by aran112000** [comment] 2024-06-27 18:02
> Does anyone know if there's a roadmap for PHP updates in the future? [Not for end of support](https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html), but rather for when to expect new versions dropping, so that we can plan upgrades accordingly.

PHP 8.4 is scheduled for stable release Nov 21 2024 (mid-late November tends to be the timeline each year for PHP):
https://wiki.php.net/todo/php84

As for when that reaches an Amazon Linux repo, expect 6-12 months later from past experiences with AL2 and AL2023.

**Comment by jtrumpio** [comment] 2024-07-07 18:48
Still not added, unless I am missing something.

**Comment by beeradmoore** [comment] 2024-07-07 21:22
> Still not added, unless I am missing something.

You need to update your Amazon Linux 2023 version. Packages are locked to specific OS releases. So if you want php8.3 you need to get AmazonLinux2023.5.whateverItWas

**Comment by jtrumpio** [comment] 2024-07-08 03:14
I'm using 2023.5.20240701 and it's still only at 8.2.18.

**Comment by beeradmoore** [comment] 2024-07-08 03:16
Are you installing with `php8.3`?
Does `def search php` show it?

**Comment by daniejstriata** [comment] 2024-07-10 16:47
Just saw this article saying AWS is definitely dropping support for older releases of PHP and would want users to favour current releases. Problem is that today some site is current and in 4 years it's legacy but can't be switched off just yet.
https://devclass.com/2024/07/08/aws-pulls-support-for-eold-but-widely-used-versions-of-php/

**Comment by beeradmoore** [comment] 2024-07-10 23:24
@daniejstriata , that article is talking about AWS SDK itself, not php runtimes in Amazon Linux 2/2023.

**Comment by stewartsmith** [comment] 2024-07-25 02:26
[AL2023.5](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240624.html) has added `php8.3` to the repositories, so resolving this issue.

**Closed by stewartsmith** 2024-07-25 02:26 UTC
Labels: enhancement, packages
