### ISSUE TITLE
Chromium: Not able to install Chromium

### ISSUE THREAD

**Issue by prathmeshp257** [amazonlinux/amazon-linux-2023#706] opened 2024-04-29 07:11 UTC
Chromium package is missing in Amazon Linux 2023

This package is available in Amazon Linux 2 via external sources such as EPEL.

**Comment by stewartsmith** [comment] 2024-05-15 17:20
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/356

**Closed by stewartsmith** 2024-05-15 17:20 UTC
Labels: duplicate, enhancement, packages
