### ISSUE TITLE
[Package Request] - gstreamer1

### ISSUE THREAD

**Issue by giladmalachi** [amazonlinux/amazon-linux-2023#847] opened 2024-11-27 15:10 UTC
**Description**
Missing Package: The all gstreamer* library is currently missing from Amazon Linux 2023.  
GStreamer is a library for constructing graphs of media-handling components. The applications it supports range from simple Ogg/Vorbis playback, audio/video streaming to complex audio (mixing) and video (non-linear editing) processing.

**Update or New Package Request**

This is a request for a new package.

**Availability in Amazon Linux 2**

The package is available for Amazon Linux 2, but it is not included in Amazon Linux 2023.

**Additional Information**

please add the all gstreamer* library

**Comment by ozbenh** [comment] 2024-11-27 23:06
Can you elaborate a bit more in the use case ? It is already under investigation in another context (graphical desktop), but the key issue with gstreamer is ... the codecs. Most codecs come with a very wide range of interesting non-technical issues (the kind that needs lawyers involved) and also have a tendency to attract CVEs. It would be useful for us to get more data on which specific codecs customers are interested in and the use cases

**Comment by giladmalachi** [comment] 2024-12-01 10:16
one of our business goal is transcoding and encoding different types of media and we use it with conjunction with Ffmpeg

**Comment by stewartsmith** [comment] 2024-12-26 20:52
Duplicate of https://github.com/amazonlinux/amazon-linux-2023/issues/241

**Closed by stewartsmith** 2024-12-26 20:52 UTC
Labels: duplicate, enhancement, packages
